apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Flask python app
  annotations:
    github.com/project-slug: NainyChowksey/python-app
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
